In [8]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact = 1
        while(n!=0):
            fact = fact * n
            n = n - 1
        return fact
    
p1= Demo1()
print(p1.fact(4))
        

24


## python, the concept oop follow these things

##  Inheritance
##  Encapsulation :-Wrap the data into single
##  polymorphism

In [20]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
            return p1+p2
c1=demo2(10,20)
print(c1.add(500,200))

    

700


# Pytho Numpy
  ## Numpy arrays is a bit like python list
  ## Numpy arrays is acentral data structure of the numpy lib
  ## lib actually short for numeric python 

In [21]:
lst = [1,2,3]
print(lst)

[1, 2, 3]


In [25]:
import numpy as np
lst = [3,5,7,8]
array = np.array(lst)
print(array)

[3 5 7 8]


In [30]:
import numpy as np
lst = [3,5,7,8]
array = np.array(lst)
print(array.shape)
print(array. dtype)

(4,)
int32


In [53]:
a1 = np.array([(3,2,6),(2,4,5)])
print(a1)
a1.reshape(3,2)

[[3 2 6]
 [2 4 5]]


array([[3, 2],
       [6, 2],
       [4, 5]])

In [34]:
a1 = np.array([(3,2,1),(2,4,5)])
print(a1.shape)

(2, 3)


In [35]:
a1 = np.array([(3,2,1),(2,4,5)])
print(a1.dtype)

int32


In [41]:
a1 = np.array([2,4,5])
a2 = np.array([3,2,1])
print(np.vstack((a1,a2)))

[[2 4 5]
 [3 2 1]]


In [42]:
a1 = np.array([2,4,5])
a2 = np.array([3,2,1])
print(np.hstack((a1,a2)))

[2 4 5 3 2 1]


In [55]:
a1 = np.random.normal([2,4,6,5])
print(a1)

[3.84379643 5.46265248 5.47835564 5.36414715]


In [57]:
a1=np.random.random([2,4])
print(a1)                     

[[0.2104243  0.8488714  0.74366968 0.95863617]
 [0.74145035 0.13923004 0.74704184 0.68864282]]


In [46]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.zeros([2,4],dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [51]:
# np.ones(shape,dtype=float,order='(')
np.ones([9,4],dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [60]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3] = 14
np.asarray(A)[2][1] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1 16  1  1]
 [ 1  1  1  1]]


In [61]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [62]:
np.arange(2,46,7)

array([ 2,  9, 16, 23, 30, 37, 44])

In [98]:
a = np.array([(3,2,1),(2,4,5),(2,5,7)])
print("first row:",a[:,0])

first row: [3 2 2]


In [65]:
a = np.array([(3,2,1),(2,4,5)])
print("first row:",a[0][1])

first row: 2


In [90]:
a = np.array([(3,2,1),(2,4,5)])
print("first row:",a[1:2])

first row: [[2 4 5]]


In [72]:
a = np.array([(3,2,1),(2,4,5)])
print(" row column:",a[0,:1])

 row column: [3]


In [74]:
#GD - GAUSSIAN distribution
a1 = np.random.normal([2,4,6,9])
print(a1)
print("min value = ",np.min(a1))
print("max value = ",np.max(a1))
print("mean value = ",np.mean(a1))
print("median value = ",np.median(a1))

[2.10523491 3.85326827 8.2735046  7.48630018]
min value =  2.1052349085346433
max value =  8.27350460141942
mean value =  5.429576989224493
median value =  5.6697842234719555


## multiply of 1D arrays

In [79]:
a1 = np.array([2,2])
a2 = np.array([2,2])
np.dot(a1,a2)

8

In [86]:
a1 = np.array([(2,2),(1,4)])
a2 = np.array([(2,2),(1,3)])
np.add(a1,a2)

array([[4, 4],
       [2, 7]])

In [81]:
a1 = np.array([(2,2),(1,4)])
a2 = np.array([(2,2),(1,3)])
np.matmul(a1,a2)

array([[ 6, 10],
       [ 6, 14]])

In [99]:
a1 = np.array([(2,2),(1,4)])
a2 = np.array([(2,2),(1,3)])
np.dot(a1,a2)

array([[ 6, 10],
       [ 6, 14]])

## import pandas as pd

In [104]:
import pandas as pd
dict = {"Name":["a","b","c","d"],
        "EmailID":["a@gmail.com","b@gmail.com","c@gmail.com","d@gmail.com"],
        "mobileNumber":[123,3455,2345,345],
       "Address":["jdsgf","dyfiuf","dgfffhfh","hgferherh"]}
b = pd.DataFrame(dict)
print(b)

  Name      EmailID  mobileNumber    Address
0    a  a@gmail.com           123      jdsgf
1    b  b@gmail.com          3455     dyfiuf
2    c  c@gmail.com          2345   dgfffhfh
3    d  d@gmail.com           345  hgferherh


In [106]:
b.index = ["1","2","3","4"]
print(b)

  Name      EmailID  mobileNumber    Address
1    a  a@gmail.com           123      jdsgf
2    b  b@gmail.com          3455     dyfiuf
3    c  c@gmail.com          2345   dgfffhfh
4    d  d@gmail.com           345  hgferherh


In [ ]:
#super market.csv - analysis (which product having higher at selling)
#which product have least selling %
